### PR TITLE
➖ Remove installer

### PR DESCRIPTION
**Pull request by CiroZDP**

### CODE REVIEW

**Comment by cliserkad** [comment]
This literally just breaks the current builds without replacing them

**Comment by CiroZDP** [comment]
> This literally just breaks the current builds without replacing them

How?

**Comment by cliserkad** [comment]
You deleted it all. But there's not a new build system yet

**Comment by CiroZDP** [comment]
Why a new build system?

**Comment by cliserkad** [comment]
ok, just create a new branch called "launcher" from this branch. Then when the launcher is complete it will replace the current system

**Comment by CiroZDP** [comment]
Ok, accept this pr first. Please

**Comment by cliserkad** [comment]
This PR breaks the current system! We won't have any working builds

**Comment by CiroZDP** [comment]
It doesn't breaks it. It deletes it.

**Comment by CiroZDP** [comment]
we could do another branch `launcher` to create another build system

**Comment by CiroZDP** [comment]
but first you'll need to accept

**Comment by cliserkad** [comment]
You can have many commits in your branch while you work on it. There's no reason to break the main branch's builds.

**Comment by CiroZDP** [comment]
But this branch is **remove installer**

**Comment by CiroZDP** [comment]
Should i rename it to **launcher**?

**Pull request closed without merging**
