### PR TITLE
use JOML for vector-based normalization

### PR DESCRIPTION
**Pull request by dankfmemes**
Should be good for a merge now.

### CODE REVIEW

**Comment by cliserkad** [comment]
Yeah this is the "correct" way of doing it. It should make adding analogue input easier.

**Comment by cliserkad** [comment]
@dankfmemes can you rebase this on main? That way you can resign the commit. Otherwise it'll be unsigned 🤷

**Comment by dankfmemes** [comment]
> @dankfmemes can you rebase this on main? That way you can resign the commit. Otherwise it'll be unsigned 🤷

Done.

**Comment by cliserkad** [comment]
Thanks!!

**Comment by cliserkad** [comment]
Ah I messed it up. I didn't realize I merged in another commit. I might require signed commits from now on.

**Pull request merged**
